
package cliente.ws.instituciones;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "InstitucionRepetidaException", targetNamespace = "http://webservices/")
public class InstitucionRepetidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InstitucionRepetidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InstitucionRepetidaException_Exception(String message, InstitucionRepetidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public InstitucionRepetidaException_Exception(String message, InstitucionRepetidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.ws.usuarios.InstitucionRepetidaException
     */
    public InstitucionRepetidaException getFaultInfo() {
        return faultInfo;
    }

}
