
package cliente.ws.usuarios;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoHayCupoEdicionTRegistro", targetNamespace = "http://webservices/")
public class NoHayCupoEdicionTRegistro_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoHayCupoEdicionTRegistro faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoHayCupoEdicionTRegistro_Exception(String message, NoHayCupoEdicionTRegistro faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoHayCupoEdicionTRegistro_Exception(String message, NoHayCupoEdicionTRegistro faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.ws.usuarios.NoHayCupoEdicionTRegistro
     */
    public NoHayCupoEdicionTRegistro getFaultInfo() {
        return faultInfo;
    }

}
