/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-11-06 19:26:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Arrays;
import java.util.List;
import com.miseventos.utils.nombreUtils;
import cliente.ws.eventos.ControladorEventoWSService;
import cliente.ws.eventos.IControladorEventoWS;
import cliente.ws.usuarios.ControladorUsuarioWSService;
import cliente.ws.usuarios.IControladorUsuarioWS;
import cliente.ws.eventos.DataEdicion;
import cliente.ws.usuarios.DataUsuario;
import cliente.ws.usuarios.DataOrganizador;
import cliente.ws.usuarios.DataDetalleRegistro;
import cliente.ws.usuarios.DataAsistente;
import cliente.ws.instituciones.DataPatrocinio;
import cliente.ws.eventos.DataPatrocinioCompleto;
import cliente.ws.eventos.DataTRegistro;
import cliente.ws.usuarios.ParEdicionRegistro;

public final class consultaEdicion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(22);
    _jspx_imports_classes.add("cliente.ws.eventos.DataTRegistro");
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("cliente.ws.eventos.ControladorEventoWSService");
    _jspx_imports_classes.add("cliente.ws.instituciones.DataPatrocinio");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataOrganizador");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("cliente.ws.eventos.IControladorEventoWS");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataDetalleRegistro");
    _jspx_imports_classes.add("cliente.ws.usuarios.ParEdicionRegistro");
    _jspx_imports_classes.add("cliente.ws.eventos.DataPatrocinioCompleto");
    _jspx_imports_classes.add("cliente.ws.usuarios.IControladorUsuarioWS");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataUsuario");
    _jspx_imports_classes.add("com.miseventos.utils.nombreUtils");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataAsistente");
    _jspx_imports_classes.add("cliente.ws.usuarios.ControladorUsuarioWSService");
    _jspx_imports_classes.add("cliente.ws.eventos.DataEdicion");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- FALTA AREGLARRR -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");

String tipo = (String) request.getAttribute("tipoUsr");
DataEdicion dataEd = (DataEdicion) request.getAttribute("dataEdicion");
DataOrganizador dataOrg = (DataOrganizador) request.getAttribute("dataOrganizador");
List<DataTRegistro> dataTRegistros = (List<DataTRegistro>) request.getAttribute("dataTRegistros");
List<DataPatrocinioCompleto> dataPatrocinios = (List<DataPatrocinioCompleto>) request.getAttribute("dataPatrocinios");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Mis Eventos :: Consulta de Edición</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Fuente -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/styles/consultaEdicionStyle.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- TOPBAR -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- SIDEBAR -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Contenido -->\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<div class=\"columna-izquierda\"></div>\r\n");
      out.write("\r\n");
      out.write("		");

		if (dataOrg != null && dataEd != null) {
			String nomNormal = nombreUtils.normalizarNombre(dataEd.getNombre());
			String nomNormal1 = nombreUtils.normalizarNombre(dataOrg.getNickname());
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Columna central -->\r\n");
      out.write("		<div class=\"columna-central\">\r\n");
      out.write("			<div class=\"contenedor-principal\">\r\n");
      out.write("				<img class=\"imagenes\"\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ED-");
      out.print( nomNormal );
      out.write(".png\"										\r\n");
      out.write("					alt=\"logoEdición\" \r\n");
      out.write("					width=\"150px\" height=\"150px\"\r\n");
      out.write("					onerror=\"this.onerror=null; this.src='");
      out.print( request.getContextPath() );
      out.write("/resources/images/IMG-NO.png';\">					\r\n");
      out.write("				<div class=\"informacion-evento\">\r\n");
      out.write("					<h2 class=\"nombre-evento\" id=\"nombreMaraton\">");
      out.print(dataEd.getNombre());
      out.write("</h2>\r\n");
      out.write("					<div class=\"detalles-evento\">\r\n");
      out.write("						<span class=\"pais\">");
      out.print(dataEd.getPais());
      out.write("</span>\r\n");
      out.write("						<span class=\"fechas\">Desde: ");
      out.print(dataEd.getFechaIni());
      out.write(" - Hasta: ");
      out.print(dataEd.getFechaFin());
      out.write("</span>\r\n");
      out.write("						<span class=\"fecha-alta\">Alta: ");
      out.print(dataEd.getFechaAlta());
      out.write("</span>\r\n");
      out.write("						<span class=\"siglas\">SIG: ");
      out.print(dataEd.getSigla());
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			");

			if (dataTRegistros != null && !dataTRegistros.isEmpty()) {
			
      out.write("\r\n");
      out.write("			<h2 class=\"texto-ed\">Tipos de Registro:</h2>\r\n");
      out.write("			<div class=\"contenedorTRegistros\">\r\n");
      out.write("				");

				for (DataTRegistro dataTR : dataTRegistros) {
				
      out.write("\r\n");
      out.write("				<div class=\"contenedor\">\r\n");
      out.write("					<div class=\"informacion-TRegistro\">\r\n");
      out.write("						<h2 class=\"nombre-evento\">");
      out.print(dataTR.getNombre());
      out.write("</h2>\r\n");
      out.write("						<div class=\"detalles-TRegistro\">\r\n");
      out.write("							<span class=\"descripcion-TRegistro\">");
      out.print(dataTR.getDescripcion());
      out.write(".</span>\r\n");
      out.write("							<span class=\"costo-TRegistro\">Costo: $");
      out.print(dataTR.getCosto());
      out.write(".</span>\r\n");
      out.write("							<span class=\"Cupos-TRegistro\">");
      out.print(dataTR.getCupo());
      out.write(" cupos restantes.</span>\r\n");
      out.write("							");

							if ("asistente".equals(session.getAttribute("tipoUsr")) && (request.getAttribute("registrado").equals(false))) {
							
      out.write("\r\n");
      out.write("							<div id=\"botondiv1\" class=\"boton-div\" style=\"display: flex;\">\r\n");
      out.write("								<button type=\"button\" class=\"btn-inscribirse\"\r\n");
      out.write("									");
 
									String eventoEncoded = java.net.URLEncoder.encode((String) request.getParameter("evento"), "UTF-8");
									String edicionEncoded = java.net.URLEncoder.encode(dataEd.getNombre(), "UTF-8");
									String nombreTREncoded = java.net.URLEncoder.encode(dataTR.getNombre(), "UTF-8");															
									
      out.write("\r\n");
      out.write("									onclick=\"window.location.href='");
      out.print( request.getContextPath() );
      out.write("/altaRegistro?evento=");
      out.print( eventoEncoded );
      out.write("&edicion=");
      out.print( edicionEncoded );
      out.write("&treg=");
      out.print( nombreTREncoded );
      out.write("'\">\r\n");
      out.write("									Inscribirse\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

			if (dataPatrocinios != null && !dataPatrocinios.isEmpty()) {
			
      out.write("\r\n");
      out.write("			<h2 class=\"texto-ed\">Patrocinan:</h2>\r\n");
      out.write("			<div class=\"contenedorTRegistros\">\r\n");
      out.write("				");

				for (DataPatrocinioCompleto dataP : dataPatrocinios) {
				
      out.write("\r\n");
      out.write("				<div class=\"contenedor\">\r\n");
      out.write("					<img class=\"imagenes\"\r\n");
      out.write("						src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/IMG-NO.png\"\r\n");
      out.write("						alt=\"logoPatro\" width=\"120px\" height=\"120px\">\r\n");
      out.write("					<div class=\"informacion-edicion\">\r\n");
      out.write("						<h2 class=\"nombre-evento\">");
      out.print(dataP.getInstitucion());
      out.write("</h2>\r\n");
      out.write("						<div class=\"detalles-edicion\">\r\n");
      out.write("							<span class=\"fecha-patrocinio\">Fecha: ");
      out.print(dataP.getFecha());
      out.write("</span>\r\n");
      out.write("							<span class=\"aporte-patrocinio\">Aporte: $");
      out.print(dataP.getMonto());
      out.write(".</span>\r\n");
      out.write("							<span class=\"nivel-patrocinio\">Nivel: ");
      out.print(dataP.getNivel());
      out.write(".</span>\r\n");
      out.write("							<span class=\"tipo-patrocinio\">Código: ");
      out.print(dataP.getCod());
      out.write(".</span>\r\n");
      out.write("							<span class=\"Cupos-patrocinio\">Cupos: ");
      out.print(dataP.getCtdCupo());
      out.write(".</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Columna derecha -->\r\n");
      out.write("		<div class=\"columna-derecha\">\r\n");
      out.write("			\r\n");
      out.write("			");
 if (dataEd.getVideoUrl() != null && !dataEd.getVideoUrl().isEmpty()) { 
      out.write("\r\n");
      out.write("			    <h2 class=\"texto-og\">Video:</h2>\r\n");
      out.write("			    <div class=\"contenedor-derecha-video\">\r\n");
      out.write("			        <iframe class=\"video-embed\"\r\n");
      out.write("			                src=\"");
      out.print( dataEd.getVideoUrl() );
      out.write("\" \r\n");
      out.write("			                frameborder=\"0\" \r\n");
      out.write("			                allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \r\n");
      out.write("			                allowfullscreen>\r\n");
      out.write("			        </iframe>\r\n");
      out.write("			    </div>\r\n");
      out.write("			    ");
 } 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<h2 class=\"texto-og\">Organiza:</h2>\r\n");
      out.write("\r\n");
      out.write("			<a href='");
      out.print( request.getContextPath() );
      out.write("/detalleUsuario?email=");
      out.print( java.net.URLEncoder.encode(dataOrg.getEmail(), "UTF-8") );
      out.write("'\r\n");
      out.write("               class=\"link-sin-estilo\">\r\n");
      out.write("				<div class=\"contenedor-derecha\">\r\n");
      out.write("					<img class=\"imagenes\"\r\n");
      out.write("						src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/USR-");
      out.print( nomNormal1 );
      out.write(".png\"										\r\n");
      out.write("					alt=\"logoEdición\" \r\n");
      out.write("					width=\"120px\" height=\"120x\"\r\n");
      out.write("					onerror=\"this.onerror=null; this.src='");
      out.print( request.getContextPath() );
      out.write("/resources/images/IMG-NO.png';\">\r\n");
      out.write("					<div class=\"informacion-TRegistro\">\r\n");
      out.write("						<h2 class=\"nombre-og\">");
      out.print(dataOrg.getNombre());
      out.write("</h2>\r\n");
      out.write("						<div class=\"detalles-TRegistro\">\r\n");
      out.write("							<span class=\"email-org\">");
      out.print(dataOrg.getEmail());
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("\r\n");
      out.write("			");

			if ("asistente".equals(session.getAttribute("tipoUsr")) && (request.getAttribute("registrado").equals(true))) {
			
      out.write("\r\n");
      out.write("			<h2 class=\"texto-registro\" id=\"registro-titulo\">Registro:</h2>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"contenedor-derecha-alt\" id=\"registro-detalle\" style=\"display: flex;\">\r\n");
      out.write("				<div class=\"informacion-TRegistro\">\r\n");
      out.write("					<div class=\"detalles-TRegistro\">\r\n");
      out.write("						");

						//Pido el controlador (su interfaz)
						IControladorUsuarioWS ICU_WS;
				    	ControladorUsuarioWSService servicio2 = new ControladorUsuarioWSService();
				        ICU_WS = servicio2.getControladorUsuarioWSPort();
				        
						DataUsuario dataU = (DataUsuario) session.getAttribute("datosUsr");
						Boolean registrado = (Boolean) request.getAttribute("registrado");
						Boolean asistio = (Boolean) ICU_WS.verificarAsistencia(dataEd.getNombre(), dataU.getNickname());
						if (registrado != null && registrado) {
							ParEdicionRegistro dataRegistro = (ParEdicionRegistro) request.getAttribute("dataRegistro");
                        	DataDetalleRegistro detalleReg = ICU_WS.getDetallesRegistro(dataU.getNickname(), dataRegistro);
						
      out.write("\r\n");
      out.write("						<div class=\"registro-item\">\r\n");
      out.write("							<span>Registrado el: ");
      out.print( detalleReg.getFecha() );
      out.write(", como: ");
      out.print( detalleReg.getNombreTR() );
      out.write("</span>\r\n");
      out.write("							");
 if (asistio){ 
      out.write("\r\n");
      out.write("								<button  id=\"descargar\" class=\"Btn\" onclick=\"window.location.href='");
      out.print( request.getContextPath() );
      out.write("/ComprobantePDF?edicion=");
      out.print( dataEd.getNombre() );
      out.write("&ciudad=");
      out.print( dataEd.getCiudad() );
      out.write("&fecha=");
      out.print( detalleReg.getFecha() );
      out.write("&evento=");
      out.print( request.getParameter("evento") );
      out.write("'\">\r\n");
      out.write("								  <svg class=\"svgIcon\" viewBox=\"0 0 384 512\" height=\"10px\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("								    <path d=\"M169.4 470.6c12.5 12.5 32.8 12.5 45.3 0l160-160c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L224 370.8 224 64c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 306.7L54.6 265.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l160 160z\"></path>\r\n");
      out.write("								  </svg>\r\n");
      out.write("								  <span class=\"icon2\" height=\"10px\"></span>\r\n");
      out.write("								</button>\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<div class=\"registro-item\">\r\n");
      out.write("							<span>Registrado (detalles no disponibles)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			");

			} else if ("organizador".equals(session.getAttribute("tipoUsr"))
					&& Boolean.TRUE.equals(request.getAttribute("organizaEdicion"))) {
				List<String> dataRegistros = (List<String>) request.getAttribute("dataRegistros");
			
      out.write("\r\n");
      out.write("			");

			if (dataRegistros != null && !dataRegistros.isEmpty()) {
			
      out.write("\r\n");
      out.write("			<h2 class=\"texto-registro\" id=\"listado-titulo\">Listado de registros:</h2>\r\n");
      out.write("			<div class=\"contenedor-derecha-alt\" id=\"listado-registros\">\r\n");
      out.write("				<div class=\"informacion-TRegistro\">\r\n");
      out.write("					<div class=\"detalles-TRegistro\">\r\n");
      out.write("						");

						for (String dataR : dataRegistros) {
						
      out.write("\r\n");
      out.write("						<div class=\"registro-item\">");
      out.print(dataR);
      out.write("</div>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
