/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-11-06 19:26:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import cliente.ws.eventos.DataEventoCompleto;
import cliente.ws.eventos.DataEdicion;
import java.util.List;
import java.util.Set;
import com.miseventos.utils.nombreUtils;

public final class consultaEvento_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("cliente.ws.eventos.DataEventoCompleto");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.miseventos.utils.nombreUtils");
    _jspx_imports_classes.add("cliente.ws.eventos.DataEdicion");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    DataEventoCompleto evento = (DataEventoCompleto) request.getAttribute("evento");
    List<DataEdicion> ediciones = (List<DataEdicion>) request.getAttribute("ediciones");
    String tipo = (String) session.getAttribute("tipoUsr");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>");
      out.print( evento.getNombre() );
      out.write(" - Mis Eventos</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Fuente -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/styles/consultaEventoStyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- TOPBAR -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- SIDEBAR -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Contenido -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"contenedores\">\r\n");
      out.write("            <div class=\"contenedor-principal\">\r\n");
      out.write("            	");
 String nomNormalEv = nombreUtils.normalizarNombre(evento.getNombre()); 
      out.write("\r\n");
      out.write("            	<img class=\"imagenes\" \r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/EV-");
      out.print( nomNormalEv );
      out.write(".png\" \r\n");
      out.write("					alt=\"logoEvento\" \r\n");
      out.write("					width=\"150px\" height=\"150px\"\r\n");
      out.write("					onerror=\"this.onerror=null; this.src='");
      out.print( request.getContextPath() );
      out.write("/resources/images/IMG-NO.png';\">\r\n");
      out.write("                <div class=\"informacion-evento\">\r\n");
      out.write("                    <h2 class=\"nombre-evento\">");
      out.print( evento.getNombre() );
      out.write("</h2>\r\n");
      out.write("                    <p class=\"descripcion-evento\">");
      out.print( evento.getDescripcion() );
      out.write("</p>\r\n");
      out.write("                    <div class=\"detalles-evento\">\r\n");
      out.write("                        <span class=\"siglas\">SIG: ");
      out.print( evento.getSigla() );
      out.write("</span>\r\n");
      out.write("                        <span class=\"fecha-alta\">Alta: ");
      out.print( evento.getFechaAlta() );
      out.write("</span>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- Mostrar categorías -->\r\n");
      out.write("                        ");
 
                        List<String> categorias = evento.getCategorias();
                        if (categorias != null && !categorias.isEmpty()) {
                            int totalCategorias = categorias.size();
                            int contador = 0;
                        
      out.write("\r\n");
      out.write("                        <span class=\"categorias-evento\">\r\n");
      out.write("                            Categorías: \r\n");
      out.write("                            ");
 
                            for (String categoria : categorias) { 
                                contador++;
                            
      out.write("\r\n");
      out.write("                                ");
      out.print( categoria );
 
                                    if (contador < totalCategorias) {
                                        out.print(", ");
                                    } else {
                                        out.print(".");
                                    }
                                
      out.write("\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if ("organizador".equals(tipo)) { 
      out.write("\r\n");
      out.write("                    <div id=\"botondiv1\" class=\"boton-div\">\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/AltaEdicion?evento=");
      out.print( java.net.URLEncoder.encode(evento.getNombre(), "UTF-8") );
      out.write("\" class=\"contenedor-link\">\r\n");
      out.write("                            <button id=\"boton1\" class=\"btn-nuevaedicion\">+ Nueva edición</button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"texto-ed\">Ediciones:</h2>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"contenedorEdiciones\">\r\n");
      out.write("                ");
 
                if (ediciones != null && !ediciones.isEmpty()) {
                    for (DataEdicion edicion : ediciones) {
                        String eventoEncoded = java.net.URLEncoder.encode(evento.getNombre(), "UTF-8");
                        String edicionEncoded = java.net.URLEncoder.encode(edicion.getNombre(), "UTF-8");
            			String nomNormal = nombreUtils.normalizarNombre(edicion.getNombre());
                
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaEdicion?evento=");
      out.print( eventoEncoded );
      out.write("&edicion=");
      out.print( edicionEncoded );
      out.write("\" class=\"contenedor-link\">\r\n");
      out.write("                    <div class=\"contenedor\">\r\n");
      out.write("                        <img class=\"imagenes\" \r\n");
      out.write("								src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ED-");
      out.print( nomNormal );
      out.write(".png\" \r\n");
      out.write("								alt=\"logoEvento\" \r\n");
      out.write("								width=\"120px\" height=\"120px\"\r\n");
      out.write("								onerror=\"this.onerror=null; this.src='");
      out.print( request.getContextPath() );
      out.write("/resources/images/IMG-NO.png';\">\r\n");
      out.write("                        <div class=\"informacion-edicion\">\r\n");
      out.write("                            <h2 class=\"nombre-evento\">");
      out.print( edicion.getNombre() );
      out.write("</h2>\r\n");
      out.write("                            <div class=\"detalles-edicion\">\r\n");
      out.write("                                <span class=\"siglas\">SIGLA: ");
      out.print( edicion.getSigla() );
      out.write("</span>\r\n");
      out.write("                                <span class=\"pais\">");
      out.print( edicion.getCiudad() );
      out.write(',');
      out.write(' ');
      out.print( edicion.getPais() );
      out.write("</span>\r\n");
      out.write("                                <span class=\"fechas\">Fecha Alta: ");
      out.print( edicion.getFechaAlta() );
      out.write("</span>\r\n");
      out.write("                                <span class=\"fechas\">Desde: ");
      out.print( edicion.getFechaIni() );
      out.write(" - Hasta: ");
      out.print( edicion.getFechaFin() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                ");
 
                    }
                } else {
                
      out.write("\r\n");
      out.write("                <p style=\"color: #f1eeee; text-align: center; margin-top: 20px;\">\r\n");
      out.write("                    No hay ediciones disponibles para este evento.\r\n");
      out.write("                </p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
