/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-11-06 19:26:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import cliente.ws.usuarios.DataUsuario;
import cliente.ws.usuarios.DataAsistente;
import cliente.ws.usuarios.DataOrganizador;
import cliente.ws.usuarios.ParEdicionRegistro;
import cliente.ws.usuarios.DataDetalleRegistro;
import cliente.ws.eventos.DataEdicionWeb;
import cliente.ws.usuarios.Estado;
import cliente.ws.eventos.ControladorEventoWSService;
import cliente.ws.eventos.IControladorEventoWS;
import cliente.ws.usuarios.ControladorUsuarioWSService;
import cliente.ws.usuarios.IControladorUsuarioWS;
import com.miseventos.utils.nombreUtils;

public final class detalleUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(18);
    _jspx_imports_classes.add("cliente.ws.eventos.ControladorEventoWSService");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataOrganizador");
    _jspx_imports_classes.add("cliente.ws.usuarios.Estado");
    _jspx_imports_classes.add("cliente.ws.eventos.DataEdicionWeb");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("cliente.ws.eventos.IControladorEventoWS");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataDetalleRegistro");
    _jspx_imports_classes.add("cliente.ws.usuarios.ParEdicionRegistro");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataUsuario");
    _jspx_imports_classes.add("cliente.ws.usuarios.IControladorUsuarioWS");
    _jspx_imports_classes.add("com.miseventos.utils.nombreUtils");
    _jspx_imports_classes.add("cliente.ws.usuarios.DataAsistente");
    _jspx_imports_classes.add("cliente.ws.usuarios.ControladorUsuarioWSService");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!--  Revisar el import este -->\r\n");
      out.write(" <!--  Revisar el import este -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    ");

		DataUsuario usr = (DataUsuario) session.getAttribute("datosUsr");
    	String loggedMail = "";
    	if (usr != null)
    		loggedMail = usr.getEmail();
        String tipo = (String) request.getAttribute("tipo");
        DataUsuario usuario = (DataUsuario) request.getAttribute("usuario");
        String nombreUsuario = usuario != null ? usuario.getNombre() : "Usuario";
        List<String> seguidos = (List<String>) request.getAttribute("seguidos");
        List<String> seguidores = (List<String>) request.getAttribute("seguidores");
    
      out.write("\r\n");
      out.write("    <title>");
      out.print( nombreUsuario );
      out.write(" - Detalle de ");
      out.print( tipo );
      out.write(" :: Mis Eventos</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Fuente -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/styles/detalleUsuarioStyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"");
      out.print( tipo != null ? tipo.toLowerCase() : "" );
      out.write("\">\r\n");
      out.write("    <!-- TOPBAR -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- SIDEBAR -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Contenido -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"contenedores\">\r\n");
      out.write("            <!-- Botón para volver -->\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/consultaUsuario\" class=\"boton-volver\">← Volver a la lista</a>\r\n");
      out.write("            \r\n");
      out.write("            ");

                if (usuario != null && tipo != null) {
                	String nomNormal = nombreUtils.normalizarNombre(usuario.getNickname());
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- Información principal del usuario -->\r\n");
      out.write("            <div class=\"contenedor-principal\">\r\n");
      out.write("            	<div class=\"contenedor-imagen-stats\">\r\n");
      out.write("	                <div class=\"imagen-usuario\">\r\n");
      out.write("	                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/USR-");
      out.print( nomNormal );
      out.write(".png\" \r\n");
      out.write("	                         alt=\"");
      out.print( usuario.getNombre() );
      out.write("\" \r\n");
      out.write("	                         onerror=\"this.style.display='none'; this.parentElement.innerHTML='Sin imagen'\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	                \r\n");
      out.write("	                <div class=\"estadisticas-usuario\">\r\n");
      out.write("						<div class=\"estadistica-item\" onclick=\"abrirModal('seguidores')\">\r\n");
      out.write("					        <div class=\"estadistica-numero\">");
      out.print( seguidores != null ? seguidores.size() : 0 );
      out.write("</div>\r\n");
      out.write("					        <div class=\"estadistica-label\">Seguidores</div>\r\n");
      out.write("					    </div>\r\n");
      out.write("					    <div class=\"estadistica-item\" onclick=\"abrirModal('seguidos')\">\r\n");
      out.write("					        <div class=\"estadistica-numero\">");
      out.print( seguidos != null ? seguidos.size() : 0 );
      out.write("</div>\r\n");
      out.write("					        <div class=\"estadistica-label\">Seguidos</div>\r\n");
      out.write("					    </div>\r\n");
      out.write("					</div>            	\r\n");
      out.write("            	</div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"informacion-usuario\">\r\n");
      out.write("                    <h1 class=\"nombre-usuario\">");
      out.print( usuario.getNombre() );
      out.write("</h1>\r\n");
      out.write("                    <p class=\"nickname-usuario\">@");
      out.print( usuario.getNickname() );
      out.write("</p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    ");
if(usuario.getEmail().equals(loggedMail)){
      out.write("\r\n");
      out.write("					    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ModificarUsuario\" class=\"boton-editar-perfil\">✏️ Editar Perfil</a>\r\n");
      out.write("					");

					} else {
						if (usr != null) {
							IControladorUsuarioWS ICU_WS;
					    	ControladorUsuarioWSService servicio2 = new ControladorUsuarioWSService();
					        ICU_WS = servicio2.getControladorUsuarioWSPort();
							boolean esSeguidor = ICU_WS.esSeguidor(usuario.getEmail(), loggedMail);
							if (esSeguidor) {
							
      out.write("\r\n");
      out.write("								<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/detalleUsuario\" method=\"POST\" style=\"display: inline;\">\r\n");
      out.write("						            <input type=\"hidden\" name=\"accion\" value=\"dejar_seguir\">\r\n");
      out.write("						            <input type=\"hidden\" name=\"emailASeguir\" value=\"");
      out.print( usuario.getEmail() );
      out.write("\">\r\n");
      out.write("						            <button type=\"submit\" class=\"boton-seguir siguiendo\">- Dejar de seguir</button>\r\n");
      out.write("						        </form>\r\n");
      out.write("							");

							} else { 
      out.write("\r\n");
      out.write("								<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/detalleUsuario\" method=\"POST\" style=\"display: inline;\">\r\n");
      out.write("						            <input type=\"hidden\" name=\"accion\" value=\"seguir\">\r\n");
      out.write("						            <input type=\"hidden\" name=\"emailASeguir\" value=\"");
      out.print( usuario.getEmail() );
      out.write("\">\r\n");
      out.write("						            <button type=\"submit\" class=\"boton-seguir\">+ Seguir</button>\r\n");
      out.write("					        	</form>\r\n");
      out.write("				        	");

							}
						}
                	}
					
      out.write("\r\n");
      out.write("                    <div class=\"detalles-usuario\">\r\n");
      out.write("                        <div class=\"detalle-item\">\r\n");
      out.write("                            <span class=\"icono\">📧</span>\r\n");
      out.write("                            <span>");
      out.print( usuario.getEmail() );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"detalle-item\">\r\n");
      out.write("                            <span class=\"icono\">👤</span>\r\n");
      out.write("                            <span>Tipo: ");
      out.print( tipo );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        ");

                            if ("Asistente".equals(tipo)) {
                                DataAsistente asistente = (DataAsistente) usuario;
                        
      out.write("\r\n");
      out.write("                                <div class=\"detalle-item\">\r\n");
      out.write("                                    <span class=\"icono\">🎂</span>\r\n");
      out.write("                                    <span>Fecha de nacimiento: ");
      out.print( asistente.getFechaNac() );
      out.write("</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"detalle-item\">\r\n");
      out.write("                                    <span class=\"icono\">📅</span>\r\n");
      out.write("                                    <span>Apellido: ");
      out.print( asistente.getApellido() );
      out.write("</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        ");

                            } else if ("Organizador".equals(tipo)) {
                                DataOrganizador organizador = (DataOrganizador) usuario;
                                if (organizador.getUrl() != null && !organizador.getUrl().isEmpty()) {
                        
      out.write("\r\n");
      out.write("                                    <div class=\"detalle-item\">\r\n");
      out.write("                                        <span class=\"icono\">🌐</span>\r\n");
      out.write("                                        <span>");
      out.print( organizador.getUrl() );
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                        ");

                                }
                                if (organizador.getDescripcion() != null && !organizador.getDescripcion().isEmpty()) {
                        
      out.write("\r\n");
      out.write("                                    <div class=\"detalle-item\">\r\n");
      out.write("                                        <span class=\"icono\">📝</span>\r\n");
      out.write("                                        <span>");
      out.print( organizador.getDescripcion() );
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                        ");

                                }
                            }
                        
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");

                if ("Asistente".equals(tipo)) {
                    @SuppressWarnings("unchecked")
                    List<ParEdicionRegistro> registros = (List<ParEdicionRegistro>) request.getAttribute("registros");
            
      out.write("\r\n");
      out.write("                    <!-- Sección de registros a eventos -->\r\n");
      out.write("                    <div class=\"seccion-registros\">\r\n");
      out.write("                        <h2 class=\"seccion-titulo\">Mis Registros a Eventos</h2>\r\n");
      out.write("                        <div class=\"contenedor-secundario\">\r\n");
      out.write("                            ");

                                if (registros != null && !registros.isEmpty() && usuario.getEmail().equals(loggedMail)) {
                            
      out.write("\r\n");
      out.write("                                    <div class=\"lista-items\">\r\n");
      out.write("                                    ");

                                    IControladorUsuarioWS ICU_WS;
                                    ControladorUsuarioWSService servicio2 = new ControladorUsuarioWSService();
                                    ICU_WS = servicio2.getControladorUsuarioWSPort();
                                    
                                    IControladorEventoWS IEV_WS;
                                    ControladorEventoWSService servicio = new ControladorEventoWSService();
                                    IEV_WS = servicio.getControladorEventoWSPort();
                                        for (ParEdicionRegistro registro : registros) {
                                        	DataDetalleRegistro DataReg = ICU_WS.getDetallesRegistro(usuario.getNickname(), registro);
                                    
      out.write("\r\n");
      out.write("                                        <div class=\"item\">\r\n");
      out.write("                                            <div class=\"info-registro\">\r\n");
      out.write("                                            	<span class=\"nombre-evento\">\r\n");
      out.write("                                                    ✅ <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaEdicion?evento=");
      out.print( java.net.URLEncoder.encode(IEV_WS.eventoTieneEdicion(registro.getNombreEdicion()), "UTF-8") );
      out.write("&edicion=");
      out.print( java.net.URLEncoder.encode(registro.getNombreEdicion(),"UTF-8") );
      out.write("\" \r\n");
      out.write("                                                    class = \"nombre-evento-link\"> \r\n");
      out.write("                                                    ");
      out.print( registro.getNombreEdicion() );
      out.write(" </a>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span class=\"detalle-registro\">\r\n");
      out.write("                                                	Tipo: ");
      out.print( DataReg.getTipoRegistro() );
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span class=\"fecha-costo\">\r\n");
      out.write("                                                	Registrado: ");
      out.print( DataReg.getFechaRegistro() );
      out.write(" - Costo: $");
      out.print( DataReg.getCosto() );
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    ");

                                        }
                                    
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                            ");

                                } else {
                            		if (usr != null && usr.getNickname().equals(usuario.getNickname())) {
                            
      out.write("\r\n");
      out.write("                            		<p style=\"text-align: center; color: #666; padding: 20px;\">\r\n");
      out.write("                                        Aún no te has registrado a ninguna edición de evento.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    ");
 
                                    } else { 
                                    
      out.write("\r\n");
      out.write("                                    <p style=\"text-align: center; color: #666; padding: 20px;\">\r\n");
      out.write("                                        Inicia sesión como ");
      out.print( usuario.getNickname() );
      out.write(" para ver sus registros.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                            ");

                            		}
                                }
                            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            ");

                } else if ("Organizador".equals(tipo)) {
                    DataEdicionWeb[] ediciones = (DataEdicionWeb[]) request.getAttribute("ediciones");
            
      out.write("\r\n");
      out.write("                    <!-- Sección de eventos organizados -->\r\n");
      out.write("                    <div class=\"seccion-eventos\">\r\n");
      out.write("                        <h2 class=\"seccion-titulo\">Ediciones de Eventos Organizadas</h2>\r\n");
      out.write("                        <div class=\"contenedor-secundario\">\r\n");
      out.write("                            ");

	                            IControladorEventoWS IEV_WS;
	                            ControladorEventoWSService servicio = new ControladorEventoWSService();
	                            IEV_WS = servicio.getControladorEventoWSPort();
                                if (ediciones != null && ediciones.length > 0) {
                            
      out.write("\r\n");
      out.write("                                    <div class=\"lista-items\">\r\n");
      out.write("                                    ");

                                        for (DataEdicionWeb edicion : ediciones) {
                                        	String evento = IEV_WS.eventoTieneEdicion(edicion.getNombre());
                                        	if(edicion.getEstado() == cliente.ws.eventos.Estado.CONFIRMADO){
                                    
      out.write("\r\n");
      out.write("                                        <div class=\"item\">\r\n");
      out.write("                                            <div class=\"info-evento\">\r\n");
      out.write("                                                <span class=\"nombre-evento\">\r\n");
      out.write("                                                    ✅ <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaEdicion?evento=");
      out.print( java.net.URLEncoder.encode(evento, "UTF-8") );
      out.write("&edicion=");
      out.print( java.net.URLEncoder.encode(edicion.getNombre(),"UTF-8") );
      out.write("\"\r\n");
      out.write("                                                    class = \"nombre-evento-link\">\r\n");
      out.write("                                                    ");
      out.print( edicion.getNombre() );
      out.write(' ');
      out.write('(');
      out.print( edicion.getSigla() );
      out.write(") </a>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span class=\"detalle-evento\">\r\n");
      out.write("                                                    Estado: Confirmada - ");
      out.print( edicion.getCiudad() );
      out.write(',');
      out.write(' ');
      out.print( edicion.getPais() );
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span class=\"fecha-evento\">\r\n");
      out.write("                                                    Fecha: ");
      out.print( edicion.getFechaIni() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( edicion.getFechaFin() );
      out.write(" | Ingresada: ");
      out.print( edicion.getFechaAlta() );
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                ");

                                                if(usuario.getEmail().equals(loggedMail)){
                                                	String edicionEncoded = java.net.URLEncoder.encode(edicion.getNombre(), "UTF-8");
													String nombreEvento = IEV_WS.eventoTieneEdicion(edicion.getNombre());
													String eventoEncoded = java.net.URLEncoder.encode(nombreEvento, "UTF-8");
                                                
      out.write("\r\n");
      out.write("				                                    <div class=\"botones-evento\">\r\n");
      out.write("					                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/altaTReg?evento=");
      out.print( eventoEncoded );
      out.write("&edicion=");
      out.print( edicionEncoded );
      out.write("\" class=\"boton-evento boton-tipo-registro\">Nuevo Tipo Registro</a>\r\n");
      out.write("														<a href=\"");
      out.print( request.getContextPath() );
      out.write("/AltaPatrocinio?evento=");
      out.print( java.net.URLEncoder.encode(evento, "UTF-8") );
      out.write("&edicion=");
      out.print( java.net.URLEncoder.encode(edicion.getNombre(),"UTF-8") );
      out.write("\" class=\"boton-evento boton-patrocinio\">Nuevo Patrocinio</a>														\r\n");
      out.write("					                                </div>\r\n");
      out.write("                    							");
} 
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    ");

                                        	 }else{
                                        		 if(usuario.getEmail().equals(loggedMail)){
                                    
      out.write("\r\n");
      out.write("                                    	<div class=\"item\">\r\n");
      out.write("                                            <div class=\"info-evento\">\r\n");
      out.write("                                                <span class=\"nombre-evento\">\r\n");
      out.write("                                                    ❌ <a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaEdicion?evento=");
      out.print( java.net.URLEncoder.encode(evento, "UTF-8") );
      out.write("&edicion=");
      out.print( java.net.URLEncoder.encode(edicion.getNombre(),"UTF-8") );
      out.write("\"\r\n");
      out.write("                                                    class = \"nombre-evento-link\">\r\n");
      out.write("                                                    ");
      out.print( edicion.getNombre() );
      out.write(' ');
      out.write('(');
      out.print( edicion.getSigla() );
      out.write(") </a>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span class=\"detalle-evento\">\r\n");
      out.write("                                                    Estado: ");
      out.print( edicion.getEstado());
      out.write(" edicion - ");
      out.print( edicion.getCiudad() );
      out.write(',');
      out.write(' ');
      out.print( edicion.getPais() );
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span class=\"fecha-evento\">\r\n");
      out.write("                                                    Fecha: ");
      out.print( edicion.getFechaIni() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( edicion.getFechaFin() );
      out.write(" | Ingresada: ");
      out.print( edicion.getFechaAlta() );
      out.write("\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>  \r\n");
      out.write("                                    ");

                                        		 }
                                        	}
                                        }
                                    
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                            ");

                                } else {
                            
      out.write("\r\n");
      out.write("                                    <p style=\"text-align: center; color: #666; padding: 20px;\">\r\n");
      out.write("                                        No hay ediciones asociadas a este organizador.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                            ");

                                }
                            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- POPUP Seguidores -->\r\n");
      out.write("    <div id=\"modalSeguidores\" class=\"modal-overlay\" onclick=\"cerrarModal(event, 'modalSeguidores')\">\r\n");
      out.write("	    <div class=\"modal-contenido\" onclick=\"event.stopPropagation()\">\r\n");
      out.write("	        <div class=\"modal-header\">\r\n");
      out.write("	            <h3>Seguidores</h3>\r\n");
      out.write("	            <button class=\"modal-cerrar\" onclick=\"cerrarModal(event, 'modalSeguidores')\">&times;</button>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"modal-body\">\r\n");
      out.write("	            ");
 
	            if (seguidores == null || seguidores.isEmpty()) { 
	            
      out.write("\r\n");
      out.write("	                <p class=\"modal-vacio\">No hay seguidores aún</p>\r\n");
      out.write("	            ");
 } else {
	            	IControladorUsuarioWS ICU_WS;
			    	ControladorUsuarioWSService servicio2 = new ControladorUsuarioWSService();
			        ICU_WS = servicio2.getControladorUsuarioWSPort();
	            	String nickNorm;
	                for (String nickname : seguidores) {
	                	String tipoSeg = ICU_WS.getTipoUsuario(nickname);
	                	nickNorm = nombreUtils.normalizarNombre(nickname);
	                	DataUsuario seg = null;
	                	if ("Asistente".equals(tipoSeg)) {
		                	try {
		                		seg = ICU_WS.getAsistente(nickname);		                		
		                	} catch (Exception e) {}
	                	} else if ("Organizador".equals(tipoSeg)) {
		                	try {
			                	seg = ICU_WS.getOrganizador(nickname);	                		
		                	} catch (Exception e) {}
		                }	                		
	                	
      out.write("\r\n");
      out.write("	                    <div class=\"modal-usuario-item\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/detalleUsuario?email=");
      out.print( java.net.URLEncoder.encode(seg.getEmail(), "UTF-8") );
      out.write("'\">\r\n");
      out.write("	                        <div class=\"modal-usuario-avatar\">\r\n");
      out.write("	                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/USR-");
      out.print( nickNorm );
      out.write(".png\" \r\n");
      out.write("			                         alt=\"");
      out.print( usuario.getNombre() );
      out.write("\" \r\n");
      out.write("			                         onerror=\"this.style.display='none'; this.parentElement.innerHTML='Sin imagen'\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"modal-usuario-nickname\">@");
      out.print( nickname );
      out.write("</div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	            ");
  }
	            } 
      out.write("\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- POPUP Seguidos -->\r\n");
      out.write("	<div id=\"modalSeguidos\" class=\"modal-overlay\" onclick=\"cerrarModal(event, 'modalSeguidos')\">\r\n");
      out.write("	    <div class=\"modal-contenido\" onclick=\"event.stopPropagation()\">\r\n");
      out.write("	        <div class=\"modal-header\">\r\n");
      out.write("	            <h3>Seguidos</h3>\r\n");
      out.write("	            <button class=\"modal-cerrar\" onclick=\"cerrarModal(event, 'modalSeguidos')\">&times;</button>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"modal-body\">\r\n");
      out.write("	            ");
 
	            if (seguidos == null || seguidos.isEmpty()) { 
	            
      out.write("\r\n");
      out.write("	                <p class=\"modal-vacio\">No hay seguidos aún</p>\r\n");
      out.write("	            ");
 } else {
	            	IControladorUsuarioWS ICU_WS;
			    	ControladorUsuarioWSService servicio2 = new ControladorUsuarioWSService();
			        ICU_WS = servicio2.getControladorUsuarioWSPort();
	            	String nickNorm;
	                for (String nickname : seguidos) {
	                	String tipoSeg = ICU_WS.getTipoUsuario(nickname);
	                	nickNorm = nombreUtils.normalizarNombre(nickname);
	                	DataUsuario seg = null;
	                	if ("Asistente".equals(tipoSeg)) {
		                	try {
		                		seg = ICU_WS.getAsistente(nickname);		                		
		                	} catch (Exception e) {}
	                	} else if ("Organizador".equals(tipoSeg)) {
		                	try {
			                	seg = ICU_WS.getOrganizador(nickname);	                		
		                	} catch (Exception e) {}
		                }	                		
	                	
      out.write("\r\n");
      out.write("	                    <div class=\"modal-usuario-item\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/detalleUsuario?email=");
      out.print( java.net.URLEncoder.encode(seg.getEmail(), "UTF-8") );
      out.write("'\">\r\n");
      out.write("	                        <div class=\"modal-usuario-avatar\">\r\n");
      out.write("	                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/USR-");
      out.print( nickNorm );
      out.write(".png\" \r\n");
      out.write("			                         alt=\"");
      out.print( usuario.getNombre() );
      out.write("\" \r\n");
      out.write("			                         onerror=\"this.style.display='none'; this.parentElement.innerHTML='Sin imagen'\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"modal-usuario-nickname\">@");
      out.print( nickname );
      out.write("</div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	            ");
  }
	            } 
      out.write("\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/scripts/detalleUsuario.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
