/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-11-06 19:26:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import excepciones.*;
import cliente.ws.usuarios.DataUsuario;
import cliente.ws.usuarios.*;
import com.miseventos.utils.nombreUtils;

public final class listarUsuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("excepciones");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("cliente.ws.usuarios");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("cliente.ws.usuarios.DataUsuario");
    _jspx_imports_classes.add("com.miseventos.utils.nombreUtils");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Consulta de Usuarios :: Mis Eventos</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Fuente -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/styles/listarUsuariosStyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- TOPBAR -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- SIDEBAR -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Contenido -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"contenedores\">\r\n");
      out.write("            <h1 class=\"seccion-titulo\">Usuarios Registrados</h1>\r\n");
      out.write("            \r\n");
      out.write("            ");

                String mensaje = (String) request.getAttribute("mensaje");
                if (mensaje != null) {
            
      out.write("\r\n");
      out.write("                <div class=\"mensaje-info\">\r\n");
      out.write("                    <p>");
      out.print( mensaje );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");

                } else {
                    DataUsuario[] usuarios = (DataUsuario[]) request.getAttribute("usuarios");
                    IControladorUsuarioWS ICU_WS;
                    ControladorUsuarioWSService servicio2 = new ControladorUsuarioWSService();
                    ICU_WS = servicio2.getControladorUsuarioWSPort();
                    
                    if (usuarios != null && usuarios.length > 0) {
            
      out.write("\r\n");
      out.write("                        <div class=\"contenedor-usuarios\">\r\n");
      out.write("            ");

                        for (DataUsuario usuario : usuarios) {
                            String tipoUsuario = "Usuario";
                            String claseTipo = "tipo-usuario";
                            String claseTarjeta = "";
                            
                            try {
                                tipoUsuario = ICU_WS.getTipoUsuario(usuario.getEmail());
                                
                                if ("Asistente".equals(tipoUsuario)) {
                                    claseTipo = "tipo-asistente";
                                    claseTarjeta = "asistente";
                                } else if ("Organizador".equals(tipoUsuario)) {
                                    claseTipo = "tipo-organizador";
                                    claseTarjeta = "organizador";
                                }
                            } catch (Exception e) {
                                // Mantener valores por defecto
                            }
                            
                            String detallesAdicionales = "";
                            
                            try {
                                if ("Asistente".equals(tipoUsuario)) {
                                    DataAsistente asistente = ICU_WS.getAsistente(usuario.getEmail());
                                    detallesAdicionales = String.format(
                                        "<div class='detalle-item'>" +
                                        "<span class='icono'>🎂</span>" +
                                        "<span>%s</span>" +
                                        "</div>",
                                        asistente.getFechaNac()
                                    );
                                } else if ("Organizador".equals(tipoUsuario)) {
                                    DataOrganizador organizador = ICU_WS.getOrganizador(usuario.getEmail());
                                    if (organizador.getDescripcion() != null && !organizador.getDescripcion().isEmpty()) {
                                        detallesAdicionales = String.format(
                                            "<div class='detalle-item'>" +
                                            "<span class='icono'>📋</span>" +
                                            "<span>%s</span>" +
                                            "</div>",
                                            organizador.getDescripcion()
                                        );
                                    }
                                    if (organizador.getUrl() != null && !organizador.getUrl().isEmpty()) {
                                        detallesAdicionales += String.format(
                                            "<div class='detalle-item'>" +
                                            "<span class='icono'>🌐</span>" +
                                            "<span>%s</span>" +
                                            "</div>",
                                            organizador.getUrl()
                                        );
                                    }
                                }
                            } catch (Exception e) {
                            	System.err.println("⚠️ Error obteniendo detalles adicionales para el usuario " + usuario.getEmail() + " (" + tipoUsuario + "): " + e.getMessage());
                            	    e.printStackTrace();
                            }
                            
                            boolean esUsuarioActual = false;
                            DataUsuario datosU = (DataUsuario) session.getAttribute("datosUsr");
                            String loggedMail = "";
                            if (datosU != null)
                            	loggedMail = datosU.getEmail();
                            if(usuario.getEmail().equals(loggedMail)){
                            	esUsuarioActual = true;
                            }
            
      out.write("\r\n");
      out.write("							<a class=\"tarjeta-usuario ");
      out.print( claseTarjeta );
      out.write(' ');
      out.print( esUsuarioActual ? "usuario-actual" : "" );
      out.write("\" \r\n");
      out.write("							   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/detalleUsuario?email=");
      out.print( java.net.URLEncoder.encode(usuario.getEmail(), "UTF-8") );
      out.write("\">\r\n");
      out.write("							    \r\n");
      out.write("							    ");
 
							        if (esUsuarioActual) { 
							    
      out.write("\r\n");
      out.write("							        <div class=\"etiqueta-usuario-actual\">Tú</div>\r\n");
      out.write("							    ");

							        } 
							        String nomNormal = nombreUtils.normalizarNombre(usuario.getNickname());
							    
      out.write("\r\n");
      out.write("							    \r\n");
      out.write("							    <div class=\"imagen-usuario\">\r\n");
      out.write("							        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/USR-");
      out.print( nomNormal );
      out.write(".png\" \r\n");
      out.write("							             alt=\"");
      out.print( usuario.getNombre() );
      out.write("\" \r\n");
      out.write("							             onerror=\"this.style.display='none'; this.nextElementSibling.style.display='flex';\">\r\n");
      out.write("							        <div class=\"sin-imagen\" style=\"display:none;\">Sin imagen</div>\r\n");
      out.write("							    </div>\r\n");
      out.write("							    \r\n");
      out.write("							    <span class=\"tipo-usuario ");
      out.print( claseTipo );
      out.write('"');
      out.write('>');
      out.print( tipoUsuario );
      out.write("</span>\r\n");
      out.write("							    \r\n");
      out.write("							    <div class=\"contenido-usuario\">\r\n");
      out.write("							        <h3 class=\"nombre-usuario\">");
      out.print( usuario.getNombre() );
      out.write("</h3>\r\n");
      out.write("							        <p class=\"nickname-usuario\">@");
      out.print( usuario.getNickname() );
      out.write("</p>\r\n");
      out.write("							        <div class=\"detalles-usuario\">\r\n");
      out.write("							            <div class=\"detalle-item\">\r\n");
      out.write("							                <span class=\"icono\">📧</span>\r\n");
      out.write("							                <span>");
      out.print( usuario.getEmail() );
      out.write("</span>\r\n");
      out.write("							            </div>\r\n");
      out.write("							            ");
      out.print( detallesAdicionales );
      out.write("\r\n");
      out.write("							        </div>\r\n");
      out.write("							    </div>\r\n");
      out.write("							</a>            \r\n");
      out.write("							");

                        }
            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("            ");

                    } else {
            
      out.write("\r\n");
      out.write("                        <p style=\"color: white; text-align: center;\">No se encontraron usuarios.</p>\r\n");
      out.write("            ");

                    }
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
