
package tarea2.cliente.ws.eventos;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EventoSinCategoriaExcepcion", targetNamespace = "http://webservices/")
public class EventoSinCategoriaExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EventoSinCategoriaExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EventoSinCategoriaExcepcion_Exception(String message, EventoSinCategoriaExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EventoSinCategoriaExcepcion_Exception(String message, EventoSinCategoriaExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: tarea2.cliente.ws.eventos.EventoSinCategoriaExcepcion
     */
    public EventoSinCategoriaExcepcion getFaultInfo() {
        return faultInfo;
    }

}
