
package tarea2.cliente.ws.instituciones;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ControladorInstitucionesWSService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8081/instituciones?wsdl")
public class ControladorInstitucionesWSService
    extends Service
{

    private final static URL CONTROLADORINSTITUCIONESWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORINSTITUCIONESWSSERVICE_EXCEPTION;
    private final static QName CONTROLADORINSTITUCIONESWSSERVICE_QNAME = new QName("http://webservices/", "ControladorInstitucionesWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/instituciones?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORINSTITUCIONESWSSERVICE_WSDL_LOCATION = url;
        CONTROLADORINSTITUCIONESWSSERVICE_EXCEPTION = e;
    }

    public ControladorInstitucionesWSService() {
        super(__getWsdlLocation(), CONTROLADORINSTITUCIONESWSSERVICE_QNAME);
    }

    public ControladorInstitucionesWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORINSTITUCIONESWSSERVICE_QNAME, features);
    }

    public ControladorInstitucionesWSService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORINSTITUCIONESWSSERVICE_QNAME);
    }

    public ControladorInstitucionesWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORINSTITUCIONESWSSERVICE_QNAME, features);
    }

    public ControladorInstitucionesWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorInstitucionesWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IControladorInstitucionesWS
     */
    @WebEndpoint(name = "ControladorInstitucionesWSPort")
    public IControladorInstitucionesWS getControladorInstitucionesWSPort() {
        return super.getPort(new QName("http://webservices/", "ControladorInstitucionesWSPort"), IControladorInstitucionesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IControladorInstitucionesWS
     */
    @WebEndpoint(name = "ControladorInstitucionesWSPort")
    public IControladorInstitucionesWS getControladorInstitucionesWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "ControladorInstitucionesWSPort"), IControladorInstitucionesWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORINSTITUCIONESWSSERVICE_EXCEPTION!= null) {
            throw CONTROLADORINSTITUCIONESWSSERVICE_EXCEPTION;
        }
        return CONTROLADORINSTITUCIONESWSSERVICE_WSDL_LOCATION;
    }

}
