
package tarea2.cliente.ws.instituciones;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PatrocinioRepetidoException", targetNamespace = "http://webservices/")
public class PatrocinioRepetidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PatrocinioRepetidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PatrocinioRepetidoException_Exception(String message, PatrocinioRepetidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public PatrocinioRepetidoException_Exception(String message, PatrocinioRepetidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: tarea2.cliente.ws.instituciones.PatrocinioRepetidoException
     */
    public PatrocinioRepetidoException getFaultInfo() {
        return faultInfo;
    }

}
