/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-11-06 14:25:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.miseventos.utils.nombreUtils;
import cliente.ws.usuarios.*;
import cliente.ws.eventos.*;
import java.util.List;

public final class detalleUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("cliente.ws.usuarios");
    _jspx_imports_packages.add("cliente.ws.eventos");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.miseventos.utils.nombreUtils");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");

DataAsistente usr = (DataAsistente) request.getAttribute("asistente");
List<ParEdicionRegistro> registros = (List<ParEdicionRegistro>) request.getAttribute("registros");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("	<title> ");
      out.print( usr.getNickname() );
      out.write(" :: Mis Eventos</title>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("        \r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/styles/detalleUsuarioStyle.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/styles/templateStyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	 <!-- TOPBAR -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- CARDS -->\r\n");
      out.write("    <div class=\"info-container\">\r\n");
      out.write("    	<!-- Card Usuario -->\r\n");
      out.write("		<div class=\"profile-card\">\r\n");
      out.write("  			<div class=\"profile-left\">\r\n");
      out.write("    			<div class=\"profile-avatar\">\r\n");
      out.write("      				<img src=\"/tarea2/resources/images/USR-");
      out.print( nombreUtils.normalizarNombre(usr.getNickname()) );
      out.write(".png\" \r\n");
      out.write("						alt=\"logoUsr\" \r\n");
      out.write("						onerror=\"this.onerror=null; this.src='");
      out.print( request.getContextPath() );
      out.write("/resources/images/stockusr.png';\">\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<p class=\"profile-nickname\">@");
      out.print( usr.getNickname() );
      out.write("</p>\r\n");
      out.write("  			</div>\r\n");
      out.write("  \r\n");
      out.write("  			<div class=\"profile-right\">\r\n");
      out.write("    			<div class=\"profile-info\">\r\n");
      out.write("      				<h2 class=\"profile-name\">");
      out.print( usr.getNombre() );
      out.write(' ');
      out.print( usr.getApellido() );
      out.write("</h2>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<a class=\"logout-button\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">\r\n");
      out.write("      				<i class=\"bi bi-box-arrow-right\"></i>\r\n");
      out.write("      				Cerrar Sesión\r\n");
      out.write("    			</a>\r\n");
      out.write("  			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- Cards Registros -->\r\n");
      out.write("    	<div class=\"registros-section\">\r\n");
      out.write("    		");
 
    		if (registros != null && !registros.isEmpty()) {
    		
      out.write("\r\n");
      out.write("    			<h2 class=\"section-title\">Mis Registros a Eventos</h2>\r\n");
      out.write("    			<div class=\"registros-container\">\r\n");
      out.write("	    			");

	    			ControladorUsuarioWSService servicio = new ControladorUsuarioWSService();
	    			IControladorUsuarioWS ICU_WS = servicio.getControladorUsuarioWSPort();
	    			ControladorEventoWSService servicio2 = new ControladorEventoWSService();
            		IControladorEventoWS IEV_WS = servicio2.getControladorEventoWSPort();
	    			for (ParEdicionRegistro par : registros) {
                    	DataDetalleRegistro DataReg = ICU_WS.getDetallesRegistro(usr.getNickname(), par);
	    			
      out.write("\r\n");
      out.write("		        		<div class=\"registro-card\">\r\n");
      out.write("		            		<a href=\"");
      out.print( request.getContextPath() );
      out.write("/consultaEdicion?evento=");
      out.print( java.net.URLEncoder.encode(IEV_WS.eventoTieneEdicion(par.getNombreEdicion()), "UTF-8") );
      out.write("&edicion=");
      out.print( java.net.URLEncoder.encode(par.getNombreEdicion(),"UTF-8") );
      out.write("\" class=\"registro-link\">\r\n");
      out.write("		                		<div class=\"registro-info\">\r\n");
      out.write("									<h3 class=\"registro-evento-nombre\">");
      out.print( par.getNombreEdicion() );
      out.write("</h3>\r\n");
      out.write("									<p class=\"registro-detalle\">Tipo: ");
      out.print( DataReg.getTipoRegistro() );
      out.write(" </p>\r\n");
      out.write("									<span class=\"registro-fecha-costo\">Fecha: ");
      out.print( DataReg.getFechaRegistro() );
      out.write(" - Costo: $");
      out.print( DataReg.getCosto() );
      out.write("</span>\r\n");
      out.write("		                		</div>\r\n");
      out.write("		            		</a>\r\n");
      out.write("		            		\r\n");
      out.write("		            		");

		            		if (!ICU_WS.verificarAsistencia(DataReg.getNombreEdicion(), usr.getNickname())) {
		            		
      out.write("\r\n");
      out.write("								<button type=\"button\" class=\"asistencia-button\" onclick=\"mostrarModalAsistencia(event, '");
      out.print( par.getNombreEdicion() );
      out.write("')\">\r\n");
      out.write("									<i class=\"bi bi-plus-circle\"></i>\r\n");
      out.write("								</button>\r\n");
      out.write("		            		");

		            		}		            		
		            		
      out.write("\r\n");
      out.write("		        		</div>\r\n");
      out.write("		        	");
 
	    			}
	    			
      out.write("\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	");

    		} else {
    		
      out.write("\r\n");
      out.write("    			<div class=\"no-regs-message\">\r\n");
      out.write("					<i class=\"bi bi-calendar-x\"></i>\r\n");
      out.write("					<p>Aún no te has registrado a ninguna edición.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("    		");
	
    		}
		    
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- POPUP Confirmacion -->\r\n");
      out.write("	<div id=\"modalAsistencia\" class=\"modal-overlay\">\r\n");
      out.write("	    <div class=\"modal-content\" onclick=\"event.stopPropagation()\">\r\n");
      out.write("	        <form id=\"formConfirmarAsistencia\" action=\"");
      out.print( request.getContextPath() );
      out.write("/detalleUsuario\" method=\"post\">\r\n");
      out.write("	            <div class=\"modal-header\">\r\n");
      out.write("	                <h3>Confirmar Asistencia</h3>\r\n");
      out.write("	                <button type=\"button\" class=\"modal-close\" onclick=\"cerrarModal()\">\r\n");
      out.write("	                    <i class=\"bi bi-x-lg\"></i>\r\n");
      out.write("	                </button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"modal-body\">\r\n");
      out.write("	                <p>¿Confirmas tu asistencia a <strong id=\"nombreEvento\"></strong>?</p>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"modal-footer\">\r\n");
      out.write("	                <button type=\"button\" class=\"modal-button cancel\" onclick=\"cerrarModal()\">Cancelar</button>\r\n");
      out.write("	                <button type=\"submit\" class=\"modal-button confirm\">Confirmar</button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            \r\n");
      out.write("	            <input type=\"hidden\" id=\"nombreEdicionInput\" name=\"nombreEdicion\" value=\"\">\r\n");
      out.write("	            <input type=\"hidden\" name=\"nickname\" value=\"");
      out.print( usr.getNickname() );
      out.write("\">\r\n");
      out.write("	        </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- LOWBAR -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/lowbar.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- SCRIPT -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/scripts/detalleUsuarioScript.js\"></script></body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
