
package cliente.ws.eventos;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EventoNoExisteExcepcion", targetNamespace = "http://webservices/")
public class EventoNoExisteExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EventoNoExisteExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EventoNoExisteExcepcion_Exception(String message, EventoNoExisteExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EventoNoExisteExcepcion_Exception(String message, EventoNoExisteExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.ws.usuarios.EventoNoExisteExcepcion
     */
    public EventoNoExisteExcepcion getFaultInfo() {
        return faultInfo;
    }

}
