Protocol=http
Host=localhost
Port=8081
Resource=NombreWebService

URLWebService1=http://localhost:8081/eventos
URLWebService2=hhttp://localhost:8081/usuarios
URLWebService3=hhttp://localhost:8081/instituciones