Protocol=http
Host=0.0.0.0
Port=7373
Resource=NombreWebService

URLWebService1=http://pcunix137.fing.edu.uy:7373/eventos
URLWebService2=http://pcunix137.fing.edu.uy:7373/usuarios
URLWebService3=http://pcunix137.fing.edu.uy:7373/instituciones