Protocol=http
Host=localhost
Port=7373
Resource=NombreWebService

URLWebService1=http://localhost:7373/eventos
URLWebService2=hhttp://localhost:7373/usuarios
URLWebService3=hhttp://localhost:7373/instituciones