
package cliente.ws.usuarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ControladorUsuarioWSService", targetNamespace = "http://webservices/", wsdlLocation = "http://pcunix137.fing.edu.uy:7373/usuarios?wsdl")
public class ControladorUsuarioWSService
    extends Service
{

    private final static URL CONTROLADORUSUARIOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORUSUARIOWSSERVICE_EXCEPTION;
    private final static QName CONTROLADORUSUARIOWSSERVICE_QNAME = new QName("http://webservices/", "ControladorUsuarioWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pcunix137.fing.edu.uy:7373/usuarios?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORUSUARIOWSSERVICE_WSDL_LOCATION = url;
        CONTROLADORUSUARIOWSSERVICE_EXCEPTION = e;
    }

    public ControladorUsuarioWSService() {
        super(__getWsdlLocation(), CONTROLADORUSUARIOWSSERVICE_QNAME);
    }

    public ControladorUsuarioWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORUSUARIOWSSERVICE_QNAME, features);
    }

    public ControladorUsuarioWSService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORUSUARIOWSSERVICE_QNAME);
    }

    public ControladorUsuarioWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORUSUARIOWSSERVICE_QNAME, features);
    }

    public ControladorUsuarioWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorUsuarioWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IControladorUsuarioWS
     */
    @WebEndpoint(name = "ControladorUsuarioWSPort")
    public IControladorUsuarioWS getControladorUsuarioWSPort() {
        return super.getPort(new QName("http://webservices/", "ControladorUsuarioWSPort"), IControladorUsuarioWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IControladorUsuarioWS
     */
    @WebEndpoint(name = "ControladorUsuarioWSPort")
    public IControladorUsuarioWS getControladorUsuarioWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "ControladorUsuarioWSPort"), IControladorUsuarioWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORUSUARIOWSSERVICE_EXCEPTION!= null) {
            throw CONTROLADORUSUARIOWSSERVICE_EXCEPTION;
        }
        return CONTROLADORUSUARIOWSSERVICE_WSDL_LOCATION;
    }

}
