
package cliente.ws.usuarios;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ErrorDetallesRegistroException", targetNamespace = "http://webservices/")
public class ErrorDetallesRegistroException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorDetallesRegistroException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ErrorDetallesRegistroException_Exception(String message, ErrorDetallesRegistroException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ErrorDetallesRegistroException_Exception(String message, ErrorDetallesRegistroException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.ws.usuarios.ErrorDetallesRegistroException
     */
    public ErrorDetallesRegistroException getFaultInfo() {
        return faultInfo;
    }

}
