
package cliente.ws.usuarios;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IControladorUsuarioWS", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IControladorUsuarioWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.ws.usuarios.DataEdicionWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getEdicionesEventoOrganizadorWebRequest", output = "http://webservices/IControladorUsuarioWS/getEdicionesEventoOrganizadorWebResponse")
    public DataEdicionWebArray getEdicionesEventoOrganizadorWeb(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/modificarAsistenteRequest", output = "http://webservices/IControladorUsuarioWS/modificarAsistenteResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/modificarAsistente/Fault/UsuarioNoExisteException")
    })
    public void modificarAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns cliente.ws.usuarios.ParEdicionRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/estaRegistradoRequest", output = "http://webservices/IControladorUsuarioWS/estaRegistradoResponse")
    public ParEdicionRegistro estaRegistrado(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/registrarAsistenteRequest", output = "http://webservices/IControladorUsuarioWS/registrarAsistenteResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://webservices/IControladorUsuarioWS/registrarAsistente/Fault/UsuarioRepetidoException")
    })
    public void registrarAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        DataAsistente arg0)
        throws UsuarioRepetidoException_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/cargarDatosRequest", output = "http://webservices/IControladorUsuarioWS/cargarDatosResponse")
    public void cargarDatos();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getTipoUsuarioRequest", output = "http://webservices/IControladorUsuarioWS/getTipoUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/getTipoUsuario/Fault/UsuarioNoExisteException")
    })
    public String getTipoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.ws.usuarios.DataAsistente
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getAsistenteRequest", output = "http://webservices/IControladorUsuarioWS/getAsistenteResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/getAsistente/Fault/UsuarioNoExisteException")
    })
    public DataAsistente getAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.ws.usuarios.DataOrganizador
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getOrganizadorRequest", output = "http://webservices/IControladorUsuarioWS/getOrganizadorResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/getOrganizador/Fault/UsuarioNoExisteException")
    })
    public DataOrganizador getOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns cliente.ws.usuarios.DataUsuarioArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getUsuariosRequest", output = "http://webservices/IControladorUsuarioWS/getUsuariosResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/getUsuarios/Fault/UsuarioNoExisteException")
    })
    public DataUsuarioArray getUsuarios()
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws AsistenteYaRegistrado_Exception
     * @throws FechaRegistroInvalidaException_Exception
     * @throws NoHayCupoEdicionTRegistro_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/nuevoRegistroRequest", output = "http://webservices/IControladorUsuarioWS/nuevoRegistroResponse", fault = {
        @FaultAction(className = AsistenteYaRegistrado_Exception.class, value = "http://webservices/IControladorUsuarioWS/nuevoRegistro/Fault/AsistenteYaRegistrado"),
        @FaultAction(className = NoHayCupoEdicionTRegistro_Exception.class, value = "http://webservices/IControladorUsuarioWS/nuevoRegistro/Fault/NoHayCupoEdicionTRegistro"),
        @FaultAction(className = FechaRegistroInvalidaException_Exception.class, value = "http://webservices/IControladorUsuarioWS/nuevoRegistro/Fault/FechaRegistroInvalidaException")
    })
    public void nuevoRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws AsistenteYaRegistrado_Exception, FechaRegistroInvalidaException_Exception, NoHayCupoEdicionTRegistro_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns cliente.ws.usuarios.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/loginRequest", output = "http://webservices/IControladorUsuarioWS/loginResponse")
    public DataUsuario login(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns cliente.ws.usuarios.DataDetalleRegistro
     * @throws ErrorDetallesRegistroException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getDetallesRegistroRequest", output = "http://webservices/IControladorUsuarioWS/getDetallesRegistroResponse", fault = {
        @FaultAction(className = ErrorDetallesRegistroException_Exception.class, value = "http://webservices/IControladorUsuarioWS/getDetallesRegistro/Fault/ErrorDetallesRegistroException")
    })
    public DataDetalleRegistro getDetallesRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        ParEdicionRegistro arg1)
        throws ErrorDetallesRegistroException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.ws.usuarios.ParEdicionRegistroArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getRegistrosAsistenteRequest", output = "http://webservices/IControladorUsuarioWS/getRegistrosAsistenteResponse")
    public ParEdicionRegistroArray getRegistrosAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/modificarOrganizadorRequest", output = "http://webservices/IControladorUsuarioWS/modificarOrganizadorResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/modificarOrganizador/Fault/UsuarioNoExisteException")
    })
    public void modificarOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.ws.usuarios.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getUsuariosRegistradosRequest", output = "http://webservices/IControladorUsuarioWS/getUsuariosRegistradosResponse")
    public StringArray getUsuariosRegistrados(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/registrarOrganizadorRequest", output = "http://webservices/IControladorUsuarioWS/registrarOrganizadorResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://webservices/IControladorUsuarioWS/registrarOrganizador/Fault/UsuarioRepetidoException")
    })
    public void registrarOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        DataOrganizador arg0)
        throws UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws ContrasenaIncorrectaException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/modificarOrganizadorConPasswordRequest", output = "http://webservices/IControladorUsuarioWS/modificarOrganizadorConPasswordResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/modificarOrganizadorConPassword/Fault/UsuarioNoExisteException"),
        @FaultAction(className = ContrasenaIncorrectaException_Exception.class, value = "http://webservices/IControladorUsuarioWS/modificarOrganizadorConPassword/Fault/ContrasenaIncorrectaException")
    })
    public void modificarOrganizadorConPassword(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws ContrasenaIncorrectaException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.ws.usuarios.DataEdicionArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorUsuarioWS/getEdicionesEventoOrganizadorRequest", output = "http://webservices/IControladorUsuarioWS/getEdicionesEventoOrganizadorResponse")
    public DataEdicionArray getEdicionesEventoOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws ContrasenaIncorrectaException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorUsuarioWS/modificarAsistenteConPasswordRequest", output = "http://webservices/IControladorUsuarioWS/modificarAsistenteConPasswordResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/IControladorUsuarioWS/modificarAsistenteConPassword/Fault/UsuarioNoExisteException"),
        @FaultAction(className = ContrasenaIncorrectaException_Exception.class, value = "http://webservices/IControladorUsuarioWS/modificarAsistenteConPassword/Fault/ContrasenaIncorrectaException")
    })
    public void modificarAsistenteConPassword(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws ContrasenaIncorrectaException_Exception, UsuarioNoExisteException_Exception
    ;

}
