
package cliente.ws.instituciones;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IControladorInstitucionesWS", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IControladorInstitucionesWS {


    /**
     * 
     * @return
     *     returns cliente.ws.instituciones.DataInstitucionArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/IControladorInstitucionesWS/listarInstitucionesRequest", output = "http://webservices/IControladorInstitucionesWS/listarInstitucionesResponse")
    public DataInstitucionArray listarInstituciones();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws PatrocinioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorInstitucionesWS/nuevoPatrocinioRequest", output = "http://webservices/IControladorInstitucionesWS/nuevoPatrocinioResponse", fault = {
        @FaultAction(className = PatrocinioRepetidoException_Exception.class, value = "http://webservices/IControladorInstitucionesWS/nuevoPatrocinio/Fault/PatrocinioRepetidoException")
    })
    public void nuevoPatrocinio(
        @WebParam(name = "arg0", partName = "arg0")
        DataPatrocinio arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws PatrocinioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws InstitucionRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/IControladorInstitucionesWS/nuevaInstitucionRequest", output = "http://webservices/IControladorInstitucionesWS/nuevaInstitucionResponse", fault = {
        @FaultAction(className = InstitucionRepetidaException_Exception.class, value = "http://webservices/IControladorInstitucionesWS/nuevaInstitucion/Fault/InstitucionRepetidaException")
    })
    public void nuevaInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        DataInstitucion arg0)
        throws InstitucionRepetidaException_Exception
    ;

}
