
package cliente.ws.eventos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ControladorEventoWSService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8081/eventos?wsdl")
public class ControladorEventoWSService
    extends Service
{

    private final static URL CONTROLADOREVENTOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADOREVENTOWSSERVICE_EXCEPTION;
    private final static QName CONTROLADOREVENTOWSSERVICE_QNAME = new QName("http://webservices/", "ControladorEventoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/eventos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADOREVENTOWSSERVICE_WSDL_LOCATION = url;
        CONTROLADOREVENTOWSSERVICE_EXCEPTION = e;
    }

    public ControladorEventoWSService() {
        super(__getWsdlLocation(), CONTROLADOREVENTOWSSERVICE_QNAME);
    }

    public ControladorEventoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADOREVENTOWSSERVICE_QNAME, features);
    }

    public ControladorEventoWSService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADOREVENTOWSSERVICE_QNAME);
    }

    public ControladorEventoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADOREVENTOWSSERVICE_QNAME, features);
    }

    public ControladorEventoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorEventoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IControladorEventoWS
     */
    @WebEndpoint(name = "ControladorEventoWSPort")
    public IControladorEventoWS getControladorEventoWSPort() {
        return super.getPort(new QName("http://webservices/", "ControladorEventoWSPort"), IControladorEventoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IControladorEventoWS
     */
    @WebEndpoint(name = "ControladorEventoWSPort")
    public IControladorEventoWS getControladorEventoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "ControladorEventoWSPort"), IControladorEventoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADOREVENTOWSSERVICE_EXCEPTION!= null) {
            throw CONTROLADOREVENTOWSSERVICE_EXCEPTION;
        }
        return CONTROLADOREVENTOWSSERVICE_WSDL_LOCATION;
    }

}
